server:
  port: 7001
eureka:
#  自我保护的配置（尽量不要配false）
  #server:
   # enable-self-preservation: false
  instance:
    hostname: localhost #eureka实例名称
  client:
    register-with-eureka: false #false 不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中西 我的职责即使维护服务实例 不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/